resources:
  - ../../meta-base

patches:
- path: app.yaml
  target:
    kind: Application
- path: app-name.patch.yaml
  target:
    kind: Application
- path: project.yaml
  target:
    kind: AppProject
- path: project-name.patch.yaml
  target:
    kind: AppProject
