apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: meta-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Meta Project
  # Allow manifests to deploy from any Git repos
  sourceNamespaces:
  - '*'
  sourceRepos:
  - 'https://github.com/daemonfire300/argo-meta-test'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: some-app-a
    server: https://kubernetes.default.svc
  - namespace: some-app-b
    server: https://kubernetes.default.svc
